### ISSUE TITLE
About the setting of Miss_rate_threshold

### ISSUE THREAD

**Issue by ShaokangHi** [valeoai/MFEval#1]
Thank you for your nice work and code.

I saw that when you calculated the (MissRate) MR, you set miss_rate_threshold=4.0. Could you tell me why you chose 4.0 as a threshold? Or are there any References?

Looking forward to your reply. Thanks in advance!

**Comment by yihongXU** [comment]
Hi,

This is just an empirical value, ideally we should set it to 2 meters as in the NuScenes Prediction task. But given the fact that current MF models injected with real-world inputs perform badly, and by examining the FDE in such methods, we decided instead to use 4 meters as the threshold (Using 2 meters is too strict to have a meaningful mAPf).

**Comment by yihongXU** [comment]
However, you can also set with different thresholds and calculated the mean mAPf as in coco detection @0.7, @0.5, etc.

Here we just use mAPf@4m.

**Comment by ShaokangHi** [comment]
Got it! Thanks a lot.
