### ISSUE TITLE
Question about false detections in Fig. 3: Impact of controlled input errors

### ISSUE THREAD

**Issue by Fujiry0** [valeoai/MFEval#3]
Thank you for your great work!

I would like to know how to generate the false detections (FP@5meters) synthetically in more detail in Fig3.

Did you add the same identity to the randomly generated detections or create a new person?

Looking forward to your reply. Thanks in advance!

**Comment by yihongXU** [comment]
Hi, 
the FP is generated by randomly selecting one ground-truth annotation, add random noise to it and give a new id.

Hope it explains better.

best,

**Comment by Fujiry0** [comment]
Thank you very much. I understood!
